### ISSUE TITLE
Failed - Virus detected??

### ISSUE THREAD

**Issue by ManNotSoHot** [EquiFox/MInjector#1]
I have been using this for awhile now.  Re-downloaded today and saw this warning today.  Windows defender is also deleting the MInject.dll when I run it.

False positive?

**Comment by EquiFox** [comment]
Most likely a false positive, code injection isn't something AV are happy about.

Feel free to download the source code, check it out and compile it yourself :) 

This way you'll be 100% sure what's running on your machine.

**Comment by ManNotSoHot** [comment]
Will do, I’m really new to a lot of this, but grasping bits of it day by day.  Appreciate the reply.
