### ISSUE TITLE
Hey, can we get in contact?

### ISSUE THREAD

**Issue by ghost** [EquiFox/MInjector#3]
I have some money and work for you if you are interested in working with mono injection. Do you have somewhere we can be in contact?

**Comment by EquiFox** [comment]
@Sufly contact@reversing,ninja

**Comment by ghost** [comment]
reversing,ninja as in reversing.ninja site?

**Comment by EquiFox** [comment]
It's my email

**Comment by ghost** [comment]
If you have discord or skype i prefer that?

**Comment by ghost** [comment]
Also i'm blind as fuck. Your email is tagged in your github.
