### ISSUE TITLE
Where is the Hide From Assemblies feature?

### ISSUE THREAD

**Issue by Colton1skees** [EquiFox/MInjector#6]
I noticed in the screenshot you posted of MInjector, there was a checkbox to hide injected assemblies from GetLoadedAssemblies?  The only checkbox on the latest release is the "Hide from AssemblyLoad Cal;back" feature.

If you don't intend to add the feature to MInjector, is it possible you could send me some code for how the feature works?

**Comment by EquiFox** [comment]
Hi,

Both security features were merged into a single one. If you enable it, GetLoadedAssemblies won't return your assembly.

**Comment by Colton1skees** [comment]
Ok thanks. Issue closed.
